### ISSUE TITLE
[CI]: add support for prereleases

### ISSUE THREAD

**Issue by adamsoderstrom** [noaignite/accelerator#168]
Benefits:
- Trying out changes in multiple projects before actually making an official release.

**Comment by maeertin** [comment]
This might not need to be added to the CI pipeline but perhaps can be achieved by manually versioning through `changeset`. Check out their section on [prereleases](https://github.com/changesets/changesets/blob/main/docs/prereleases.md). Although it almost sounds as they warn against this due to the complexity we could give a shot if we find the need :)

**Comment by maeertin** [comment]
Closing as there no action to take.
